Vagrant Version bump 1.0.7
Islandora-Labs/islandora_vagrant pull request #154
Opened 2018-11-01 11:50 UTC by DonRichards

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2329

# What does this Pull Request do?
Updates the vagrant box version 

# What's new?
update  config.vm.box_version = "~> 1.0.6" to 1.0.7

# How should this be tested?
Vagrant up and verify the correct version is running.

# Additional Notes:
Please verify v1.0.7 is showing up on https://app.vagrantup.com/islandora/boxes/islandora-base before you begin. This PR was submitted before anyone from the community was asked to generate and post the new version. 

# Interested parties
@Islandora-Labs/committers

2018-11-01 17:08 UTC, bryjbrown commented
@DonRichards I just tested, and it exits almost immediately with:
```
The box you're attempting to add has no available version that
matches the constraints you requested. Please double-check your
settings. Also verify that if you specified version constraints,
that the provider you wish to use is available for these constraints.

Box: islandora/islandora-base
Address: https://vagrantcloud.com/islandora/islandora-base
Constraints: ~> 1.0.7
Available versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6
```

Have you actually exported 1.0.7 and pushed to atlas yet?

2018-11-01 19:34 UTC, dannylamb commented
@DonRichards @bryjbrown I have access to atlas and can push up an exported vm.

2018-11-06 18:01 UTC, dannylamb commented
I'm having a fun time uploading 4 GB uninterrupted, but it's on its way I promise.

2018-11-07 02:46 UTC, bryjbrown commented
@dannylamb How'd it go? I'm still seeing 1.0.6 on https://app.vagrantup.com/islandora.

2018-11-07 14:57 UTC, dannylamb commented
Still uploading :sob:  Crapped out on me last night even though I set my computer not to sleep.  So I kicked it off again this morning and hopefully I'll make it through.

2018-11-07 22:18 UTC, dannylamb commented
https://app.vagrantup.com/islandora/boxes/islandora-base/versions/1.0.7 is a go

2018-11-07 22:19 UTC, bryjbrown commented
@dannylamb 

HELL

YEAH

:sunglasses:

2018-11-07 22:30 UTC, bryjbrown commented
@DonRichards @dannylamb Downloading the new box now to build the machine. I'll approve this PR on a successful build and we can merge and finally test that blocker.

2018-11-08 15:34 UTC, bryjbrown commented
@dannylamb So I finally got the new base box pulled in, but the machine failed with the following error:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'islandora/islandora-base'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'islandora/islandora-base' is up to date...
==> default: Setting the name of the VM: Islandora 7.x-1.x Development VM
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 3306 (guest) => 3306 (host) (adapter 1)
    default: 8000 (guest) => 8000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

I tried switching back to the main 7.x branch thats using the older 1.0.6 version of the base box to see if its a problem with my vagrant or the base box, and now the 7.x branch fails with the same error message. Vagrant seemed to be working just fine until I imported this new box, are you familiar with this error or know what might have caused it? I can't use Vagrant until I get it resolved, which means I'm really handcuffed in terms of release testing stuff.

2018-11-08 15:45 UTC, dannylamb commented
@brjbrown Not sure what's happening to ya.  Let me give it a shot too and see if it happens to me.  At least then we'll be in the same boat.

2018-11-08 15:47 UTC, dannylamb commented
@bryjbrown Just occured to me, I've seen this before when I had two boxes going at the same time that tried to use port 2222 for ssh.  Are you running a claw box or something as well?

2018-11-08 15:49 UTC, DiegoPino commented
@bryjbrown probably related to what @dannylamb says about two boxes having same, do a vagrant global-status and see if some box is stuck. Also maybe you both have different Virtualbox and Vagrant versions and the export does not match your current Vagrant´s VM expectations.
Some documentation here https://github.com/hashicorp/vagrant/issues/8157
Options are:
try `vagrant destroy` before trying to do a `vagrant up`. Just to be sure
also, maybe something related to the network interface https://github.com/hashicorp/vagrant/issues/8157#issuecomment-304492943 and the different versions of Vbox? that line forces the VM to simulate a connected cable on the Virtual interface

2018-11-08 17:02 UTC, dannylamb commented
@brjbrown Whelp... I can recreate it.  Pulled in the PR, `vagrant up`, but it didn't download the new basebox.  So I `vagrant destroy; vagrant up`d and it pulled down the new base box before promptly stalling at ssh'ing in.

2018-11-08 17:08 UTC, bryjbrown commented
@dannylamb Just to confirm I'm reading your message correctly, after downloading the new base box you ran into the same issue I did?

Can you try destroying that machine and attempting to build the 7.x branch with 1.0.6 and see if you run into the same issue? Because I'm having this issue across the board now, even after completely blowing away my ~/.vagrand.d directory to make absolutely sure no pre-existing machines are mucking things up.

2018-11-08 17:16 UTC, dannylamb commented
@bryjbrown Yeah I can try.  Hilariously, vagrant ssh totally works, but is asking me for user/pass instead of just goin' right in.  Not sure how a new base box could cause this behaviour, but that's what appears to be happening :man_shrugging: 

I exported the box using `vagrant package`... I wonder if I did something wrong there.

2018-11-08 17:29 UTC, dannylamb commented
@bryjbrown So, initially, yes, reverting gave me the same issue.  I went into the Vagrantfile and forced it to use 1.0.6 instead of any sort of fuzzy matching that would still accept 1.0.7, e.g.

```diff
daniel@daniel-Latitude-3560:~/Code/Environments/islandora_vagrant$ git diff
diff --git a/Vagrantfile b/Vagrantfile
index c252603..81e9200 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -25,7 +25,7 @@ Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   
   # This is a RC VM, So make sure people are running the latest base box by April 2018
   # Which will include cantaloupe IIIF Image Server
-   config.vm.box_version = "~> 1.0.6"
+   config.vm.box_version = "1.0.6"
    config.vm.box_check_update = true
 
   unless  $forward.eql? "FALSE"  
```

And now everything is fine.  So it's defnitely the base box.  I'll try re-exporting and see if that changes anything.  Not sure how to test without having to do the push to atlas, which takes ~10 hours with my internet.

@DiegoPino @rosiel @ruebot Release Managers Emeritus assemble!  Is there anything special I need to do when exporting the base box other than `vagrant package --box <VM NAME>`?  The README suggests `config.ssh.insert_key = false` in the base box's Vagrantfile, which is what I'm about to try.  But hoping maybe one of you has some insight I'm lacking.

2018-11-08 17:36 UTC, bryjbrown commented
@dannylamb Ah, okay, wasn't aware that `~> 1.0.6` would use 1.0.7 if available, should have guessed though. I'm re-downloading 1.0.6 now on a fresh build to verify that this works.

2018-11-08 17:39 UTC, dannylamb commented
Let me know how it goes.  I"m stuck waiting for this basebox to rebuild so I can re-export it.  

Gosh we seem to compile a lot from source... :weary:

2018-11-08 17:41 UTC, br2490 commented
@dannylamb I believe you are correct - you must include that in the base Vagrantfile before building + packaging.
I've rebuilt the box and it works. I can push to my own repo (1gbps line) for testing here? If it works you could create a token for me and give me a URI to upload to re:  https://www.vagrantup.com/docs/vagrant-cloud/boxes/create.html https://app.vagrantup.com/settings/security

2018-11-08 17:44 UTC, dannylamb commented
@br2490 Yasssss, if you can upload faster that'd be great.  I'm looking into creating a token for you now.

2018-11-08 17:49 UTC, bryjbrown commented
@dannylamb @br2490 If we really DO need that, then we definitely need a PR to make sure that gets included in the upstream https://github.com/Islandora-Labs/islandora_vagrant_base_box repo so that we don't hit this issue again.

2018-11-08 17:50 UTC, dannylamb commented
@bryjbrown Good point, it really should be in there by default

2018-11-08 17:55 UTC, dannylamb commented
@br2490 Ok, if you've got a working box, I've got a token.  I can send you the token privately in IRC or Skype or something if you're ready.

2018-11-08 17:56 UTC, br2490 commented
@bryjbrown @dannylamb 
```
  config.vm.box = "benjaminrosner/islandora-base"
  config.vm.box_version = "1.0.7"
```

2018-11-08 18:00 UTC, dannylamb commented
@br2490 `vagrant up` :rocket:

I'll have to download the base box again which'll take a few.  I'll let you know if I make it past the SSH step.

2018-11-08 18:05 UTC, DiegoPino commented
@bryjbrown @dannylamb only issue I see with ~> 1.0.6 instead of  ~> 1.0.7 is that if people are unaware (or not reading) of a new base box version and are not force updating base box their local installations will always opt for their already downloaded and cached one == old

2018-11-08 18:09 UTC, bryjbrown commented
@DiegoPino I think the goal of the PR is to bump it up to `~> 1.0.7` so that anyone using the newest Islandora Vagrant downloads the new base box automatically. I think we're only reverting temporarily while trying to diagnose the problem.

2018-11-08 18:10 UTC, br2490 commented
@DiegoPino and I may misunderstanding completely but I think that may be resolved in the Vagrantfile (was about to write Dockerfile) with the setting `config.vm.box_check_update = true` which forces check and download of new ~~image~~ box (yea, I'm still in `Docker` land)

2018-11-08 18:13 UTC, bryjbrown commented
@dannylamb @br2490 I can confirm that 1.0.6 does in fact boot up properly when I set the version to strictly to use 1.0.6, so just more proof that the issue is solely with 1.0.7.

2018-11-08 18:13 UTC, DiegoPino commented
@br2490 almost  true
> "
config.vm.box_check_update (boolean) - If true, Vagrant will check for updates to the configured box on every vagrant up. If an update is found, Vagrant will tell the user. By default this is true. Updates will only be checked for boxes that properly support updates (boxes from HashiCorp's Vagrant Cloud or some other versioned box)."

Which means it will "tell" the user but won't stop and download it. That is why i was refering to "if people are unaware (**or not reading)** of a new base box version a"

2018-11-08 18:16 UTC, br2490 commented
>  **(or not reading)** 

Guilty as charged. :)

2018-11-08 18:20 UTC, DiegoPino commented
it seems this post covers all the bases for this issue 

https://github.com/hashicorp/vagrant/issues/5186

Not remember having this issue previously but also vagrant has changed quite a bit. I'm also a lot in Docker la-la-land as my fellow colleague @br2490 so could be super mistaken.

2018-11-08 18:22 UTC, dannylamb commented
I'm with @DiegoPino and would prefer `1.0.7` over `~> 1.0.7` just to force the box download.

I can also confirm we get past the SSH step with @br2490's base box.

2018-11-08 18:23 UTC, DiegoPino commented
@br249++ 👏

2018-11-08 18:24 UTC, dannylamb commented
Re-reading what I just wrote makes no sense.... but I _would_ like to force the box download, however we could do that (if possible).

2018-11-08 18:36 UTC, dannylamb commented
I've delivered an api token to @br2490 so hopefully we'll have a new basebox up there soon @bryjbrown.

2018-11-08 18:37 UTC, bryjbrown commented
@dannylamb @DiegoPino I can confirm that when I built the box initially it was `~> 1.0.7` and it did start downloading 1.0.7 without prompting me for any input, but in the spirit of no-buggedness, I'd say that we should amend the PR so that the Vagrantfile is s/~> 1.0.7/1.0.7 just to be super duper clear because fuzzy version matching is the devil. Also, I assume we're going to be pushing version update PRs along with base box updates in the future, so its a good precedent to set.

2018-11-08 18:44 UTC, dannylamb commented
^^ Heads up, just made a PR to add that line into the Vagrantfile so we don't have to do this dance ever again.

2018-11-08 19:12 UTC, dannylamb commented
Ok, @br2490 has re-uploaded the base box, and I'm retrying again.  It's re-downloading the base box... so... give me a bit.

FYI I had to `vagrant box remove islandora/islandora-base --all` before hand to clobber the borked base box I uploaded.

2018-11-08 19:29 UTC, dannylamb commented
booyah

```
daniel@daniel-Latitude-3560:~/Code/Environments/islandora_vagrant$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'islandora/islandora-base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 1.0.7
==> default: Loading metadata for box 'islandora/islandora-base'
    default: URL: https://vagrantcloud.com/islandora/islandora-base
==> default: Adding box 'islandora/islandora-base' (v1.0.7) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/islandora/boxes/islandora-base/versions/1.0.7/providers/virtualbox.box
==> default: Successfully added box 'islandora/islandora-base' (v1.0.7) for 'virtualbox'!
==> default: Importing base box 'islandora/islandora-base'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'islandora/islandora-base' is up to date...
==> default: Setting the name of the VM: Islandora 7.x-1.x Development VM
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 3306 (guest) => 3306 (host) (adapter 1)
    default: 8000 (guest) => 8000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
```

I think we're good to go here.

2018-11-08 19:30 UTC, bryjbrown commented
@dannylamb Are we still wanting to change `~> 1.0.7` to just `1.0.7`? Or do we want to merge as-is? Either way, I can take care of making a 7.x-1.12 release PR later today.

2018-11-08 19:31 UTC, dannylamb commented
I'd make it strict to `1.0.7`, but that's just me.

2018-11-08 19:33 UTC, bryjbrown commented
@dannylamb I agree wholeheartedly.

@DonRichards Can you update your PR to change the version from `~> 1.0.7` to just `1.0.7`?

2018-11-08 19:34 UTC, bryjbrown requested changes

2018-11-08 19:34 UTC, bryjbrown commented on Vagrantfile
> +   config.vm.box_version = "~> 1.0.7"
This should be changed to: 
`config.vm.box_version = "1.0.7"`

2018-11-08 19:43 UTC, dannylamb commented
The `vagrant up` just finished and we have lift-off

```
vagrant@islandora:~$ ffmpeg2theora 
ffmpeg2theora 0.29

	Xiph.Org libtheora 1.1 20090822 (Thusnelda)
	Xiph.Org libVorbis 1.3.2
	FFmpeg	 libavcodec 54.35.1
	FFmpeg	 libavformat 54.20.4


  Usage: ffmpeg2theora [options] input
```

2018-11-08 19:46 UTC, bryjbrown commented
@dannylamb Actually, since speed is a benefit here, we could also just merge this PR as-is and I could make a second PR changing it to 1.0.7 along with the release PR that does the exact same thing. Whatcha think?

2018-11-08 20:09 UTC, dannylamb commented
@bryjbrown Do it

2018-11-08 20:10 UTC, bryjbrown approved these changes

2018-11-08 20:10 UTC, merged